# Generated by Django 2.2 on 2019-04-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_area_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='whiteboards',
        ),
    ]
