# Generated by Django 2.2 on 2019-04-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0004_remove_area_whiteboards'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='whiteboards',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='whiteboard.Whiteboard'),
        ),
    ]
