# Generated by Django 2.2 on 2019-04-13 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0017_auto_20190413_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='whiteboard',
            field=models.ForeignKey(default=True, on_delete=models.SET(None), to='whiteboard.Whiteboard'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 13, 16, 42, 4, 107650, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='2019-04-13/'),
        ),
    ]
