# Generated by Django 2.2 on 2019-04-13 16:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0018_auto_20190413_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 13, 16, 43, 21, 720638, tzinfo=utc)),
        ),
    ]
