# Generated by Django 2.2 on 2019-04-13 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0019_auto_20190413_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='new_whiteboard_on_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 13, 16, 45, 27, 622540, tzinfo=utc)),
        ),
    ]
