# Generated by Django 2.2 on 2019-04-13 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0022_auto_20190413_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='new_whiteboard_on_create',
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 13, 16, 55, 2, 348061, tzinfo=utc)),
        ),
    ]
