# Generated by Django 2.2 on 2019-04-13 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0023_auto_20190413_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 13, 16, 58, 40, 57322, tzinfo=utc)),
        ),
    ]
