# Generated by Django 2.2 on 2019-04-17 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0024_auto_20190413_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='whiteboard',
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 17, 19, 3, 1, 575706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='2019-04-17/'),
        ),
    ]
