# Generated by Django 2.2 on 2019-04-23 14:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0025_auto_20190417_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='selected_whiteboards',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='whiteboard.Whiteboard'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 23, 14, 44, 1, 929153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='2019-04-23/'),
        ),
    ]
