# Generated by Django 2.2 on 2019-04-28 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0030_auto_20190428_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 17, 53, 50, 47559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='owners_folder',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
