# Generated by Django 2.2 on 2019-04-28 17:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0031_auto_20190428_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owners_folder',
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 17, 54, 37, 738788, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='2019-04-28/a'),
        ),
    ]
