# Generated by Django 2.2 on 2019-04-28 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0032_auto_20190428_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owners_folder',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 17, 55, 10, 487630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='2019-04-28/<django.db.models.fields.CharField>'),
        ),
    ]
