# Generated by Django 2.2 on 2019-04-28 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0034_auto_20190428_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='owners_folder',
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 28, 18, 2, 57, 431212, tzinfo=utc)),
        ),
    ]
