# Generated by Django 2.2 on 2019-05-18 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0036_auto_20190510_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='last_held',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 18, 13, 41, 17, 448084, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 18, 13, 41, 17, 443348, tzinfo=utc)),
        ),
    ]
