# Generated by Django 2.2 on 2019-05-18 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0037_auto_20190518_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='last_held',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 18, 13, 41, 44, 501793, tzinfo=utc)),
        ),
    ]
